
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Button IsbnButton;

	private global::Gtk.Label Isbn_Text_Block;

	private global::Gtk.Entry IsbnEntry;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("ISBN Check");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.WidthRequest = 320;
		this.fixed1.HeightRequest = 240;
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.IsbnButton = new global::Gtk.Button();
		this.IsbnButton.CanFocus = true;
		this.IsbnButton.Name = "IsbnButton";
		this.IsbnButton.UseUnderline = true;
		this.IsbnButton.Relief = ((global::Gtk.ReliefStyle)(1));
		this.IsbnButton.Label = global::Mono.Unix.Catalog.GetString("Check");
		this.fixed1.Add(this.IsbnButton);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.IsbnButton]));
		w1.X = 220;
		w1.Y = 80;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Isbn_Text_Block = new global::Gtk.Label();
		this.Isbn_Text_Block.Name = "Isbn_Text_Block";
		this.Isbn_Text_Block.Xpad = 20;
		this.Isbn_Text_Block.LabelProp = global::Mono.Unix.Catalog.GetString("Enter ISBN");
		this.Isbn_Text_Block.Justify = ((global::Gtk.Justification)(3));
		this.fixed1.Add(this.Isbn_Text_Block);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Isbn_Text_Block]));
		w2.X = 96;
		w2.Y = 200;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.IsbnEntry = new global::Gtk.Entry();
		this.IsbnEntry.CanFocus = true;
		this.IsbnEntry.Name = "IsbnEntry";
		this.IsbnEntry.IsEditable = true;
		this.IsbnEntry.InvisibleChar = '●';
		this.fixed1.Add(this.IsbnEntry);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.IsbnEntry]));
		w3.X = 10;
		w3.Y = 80;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 320;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.IsbnButton.Clicked += new global::System.EventHandler(this.OnIsbnButtonClicked);
		this.IsbnEntry.Activated += new global::System.EventHandler(this.OnIsbnButtonClicked);
	}
}
